# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DATA_PATH": "00_data.ipynb",
         "acquire_data": "00_data.ipynb",
         "rmtree": "00_data.ipynb",
         "load_custom_data": "00_data.ipynb",
         "load_data": "00_data.ipynb",
         "pad_trajectories": "00_data.ipynb",
         "normalize_trajectory": "00_data.ipynb",
         "get_custom_dls": "00_data.ipynb",
         "get_discriminative_dls": "00_data.ipynb",
         "get_turning_point_dls": "00_data.ipynb",
         "get_1vall_dls": "00_data.ipynb",
         "get_validation_dl": "00_data.ipynb",
         "get_dls_from_ds": "00_data.ipynb",
         "create_custom_dataset": "00_data.ipynb",
         "cut_trajectory": "00_data.ipynb",
         "validate_model": "00_data.ipynb",
         "validate_task": "00_data.ipynb",
         "mask_normalisation": "01_models.ipynb",
         "mask_concat_pool": "01_models.ipynb",
         "get_act": "01_models.ipynb",
         "custom_splitter": "01_models.ipynb",
         "custom_f1": "01_models.ipynb",
         "Permute": "01_models.ipynb",
         "MyLearner": "01_models.ipynb",
         "RNNLearner": "01_models.ipynb",
         "MeanPredict": "01_models.ipynb",
         "Classifier": "01_models.ipynb",
         "PoolingClassifier": "01_models.ipynb",
         "SimpleLSTM": "01_models.ipynb",
         "ConcatPoolLSTM": "01_models.ipynb",
         "RegLSTMLin": "01_models.ipynb",
         "RegLSTM": "01_models.ipynb",
         "CustomXResNet": "01_models.ipynb",
         "CNNLin": "01_models.ipynb",
         "CNN": "01_models.ipynb",
         "RNNCNNClassifier": "01_models.ipynb",
         "Ensemble": "01_models.ipynb",
         "Hydra": "01_models.ipynb",
         "CNNonRNN": "02_prototypes.ipynb",
         "save_model": "03_utils.ipynb",
         "load_model": "03_utils.ipynb",
         "plot_conf_mat": "04_analysis.ipynb",
         "get_conf_mat": "04_analysis.ipynb"}

modules = ["data.py",
           "models.py",
           "prototypes.py",
           "utils.py",
           "analysis.py"]

doc_url = "https://BorjaRequena.github.io/andi_unicorns/"

git_url = "https://github.com/BorjaRequena/andi_unicorns/tree/master/"

def custom_doc_links(name): return None
