# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_prototypes.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastai.vision.all import *
from fastai.text.all import *

from .models import *
from .data import *
from .utils import save_model, load_model