# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_utils.ipynb (unless otherwise specified).

__all__ = ['save_model', 'load_model']

# Cell
def save_model(model, name):
    "Saves trained `model` with name `name`"
    path = Path(f"../models/{name}.pth")
    torch.save(model, path)

def load_model(name):
    "Loades pre-trained model wtih name `name`."
    path = Path(f"../models/{name}.pth")
    return torch.load(path)